Script started on Tue 06 Nov 2012 09:14:52 AM PST
 ____________________________________________________________________ 
/ __        __   _                            ____             _     \
| \ \      / /__| | ___ ___  _ __ ___   ___  | __ )  __ _  ___| | __ |
|  \ \ /\ / / _ \ |/ __/ _ \| '_ ` _ \ / _ \ |  _ \ / _` |/ __| |/ / |
|   \ V  V /  __/ | (_| (_) | | | | | |  __/ | |_) | (_| | (__|   <  |
|    \_/\_/ \___|_|\___\___/|_| |_| |_|\___| |____/ \__,_|\___|_|\_\ |
|                                                                    |
|   ____           _                     _                           |
|  / ___|_ __ __ _| |__   __ _ _ __ ___ | |                          |
| | |  _| '__/ _` | '_ \ / _` | '_ ` _ \| |                          |
| | |_| | | | (_| | | | | (_| | | | | | |_|                          |
|  \____|_|  \__,_|_| |_|\__,_|_| |_| |_(_)                          |
\                                                                    /
 -------------------------------------------------------------------- 
       \   ,__,
        \  (..)____
           (__)    )\
              ||--|| *
{ggreving:lab5}$ gdb uninit
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-50.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /afs/cats.ucsc.edu/users/a/ggreving/Private/CMPS012/lab5/uninit...done.
(gdb) breakm[K main
Breakpoint 1 at 0x400503: file uninit.c, line 8.
(gdb) run
Starting program: /afs/cats.ucsc.edu/users/a/ggreving/Private/CMPS012/lab5/uninit 

Breakpoint 1, main (argc=1, argv=0x7fffffffe328) at uninit.c:8
8	   printf ("%d\n", foo);
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.47.el6_2.12.x86_64
(gdb) print foo
$1 = 32767
(gdb) step
32767
10	   printf ("%d\n", *pointer);
(gdb) print pointer
$2 = (int *) 0x0
(gdb) step

Program received signal SIGSEGV, Segmentation fault.
0x000000000040051e in main (argc=1, argv=0x7fffffffe328) at uninit.c:10
10	   printf ("%d\n", *pointer);
(gdb) quit
A debugging session is active.

	Inferior 1 [process 30061] will be killed.

Quit anyway? (y or n) y
{ggreving:lab5}$ exit
exit

Script done on Tue 06 Nov 2012 09:15:55 AM PST
