Script started on Tue 06 Nov 2012 09:28:07 AM PST
 ____________________________________________________________________ 
/ __        __   _                            ____             _     \
| \ \      / /__| | ___ ___  _ __ ___   ___  | __ )  __ _  ___| | __ |
|  \ \ /\ / / _ \ |/ __/ _ \| '_ ` _ \ / _ \ |  _ \ / _` |/ __| |/ / |
|   \ V  V /  __/ | (_| (_) | | | | | |  __/ | |_) | (_| | (__|   <  |
|    \_/\_/ \___|_|\___\___/|_| |_| |_|\___| |____/ \__,_|\___|_|\_\ |
|                                                                    |
|   ____           _                     _                           |
|  / ___|_ __ __ _| |__   __ _ _ __ ___ | |                          |
| | |  _| '__/ _` | '_ \ / _` | '_ ` _ \| |                          |
| | |_| | | | (_| | | | | (_| | | | | | |_|                          |
|  \____|_|  \__,_|_| |_|\__,_|_| |_| |_(_)                          |
\                                                                    /
 -------------------------------------------------------------------- 
       \   ,__,
        \  (..)____
           (__)    )\
              ||--|| *
{ggreving:lab5}$ valgrind malloc
==31056== Memcheck, a memory error detector
==31056== Copyright (C) 2002-2010, and GNU GPL'd, by Julian Seward et al.
==31056== Using Valgrind-3.6.0 and LibVEX; rerun with -h for copyright info
==31056== Command: malloc
==31056== 
0x4c23090-> {6, (nil)}
==31056== 
==31056== HEAP SUMMARY:
==31056==     in use at exit: 16 bytes in 1 blocks
==31056==   total heap usage: 2 allocs, 1 frees, 32 bytes allocated
==31056== 
==31056== LEAK SUMMARY:
==31056==    definitely lost: 16 bytes in 1 blocks
==31056==    indirectly lost: 0 bytes in 0 blocks
==31056==      possibly lost: 0 bytes in 0 blocks
==31056==    still reachable: 0 bytes in 0 blocks
==31056==         suppressed: 0 bytes in 0 blocks
==31056== Rerun with --leak-check=full to see details of leaked memory
==31056== 
==31056== For counts of detected and suppressed errors, rerun with: -v
==31056== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 6 from 6)
{ggreving:lab5}$ gdb mak[Klloc
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-50.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /afs/cats.ucsc.edu/users/a/ggreving/Private/CMPS012/lab5/malloc...done.
(gdb) break main
Breakpoint 1 at 0x400594: file malloc.c, line 13.
(gdb) run
Starting program: /afs/cats.ucsc.edu/users/a/ggreving/Private/CMPS012/lab5/malloc 

Breakpoint 1, main (argc=1, argv=0x7fffffffe328) at malloc.c:13
13	   node_ref ptr = malloc (sizeof (struct node));
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.47.el6_2.12.x86_64
(gdb) print ptr
$1 = (node_ref) 0x4004a0
(gdb) ptrint[K[K[K[K[Krint *ptr
$2 = {value = -1991643855, link = 0x495450f0e48348e2}
(gdb) steo
Undefined command: "steo".  Try "help".
(gdb) step
14	   ptr = malloc (sizeof (struct node));
(gdb) print ptr
$3 = (node_ref) 0x601010
(gdb) p[Kprint *ptr
$4 = {value = 0, link = 0x0}
(gdb) step
15	   ptr->value = 6;
(gdb) step
16	   ptr->link = NULL;
(gdb) step
17	   printf ("%p-> {%d, %p}\n", ptr, ptr->value, ptr->link);
(gdb) print otr[K[K[Kptr
$5 = (node_ref) 0x601030
(gdb) ptrin[K[K[K[Krint *ptr
$6 = {value = 6, link = 0x0}
(gdb) step
0x601030-> {6, (nil)}
18	   free (ptr);
(gdb) dyrp[K[K[K[Kstep
19	   return EXIT_SUCCESS;
(gdb) step
20	}
(gdb) step
0x00000037aaa1ecdd in __libc_start_main () from /lib64/libc.so.6
(gdb) quit
A debugging session is active.

	Inferior 1 [process 31063] will be killed.

Quit anyway? (y or n) y
{ggreving:lab5}$ exit
exit

Script done on Tue 06 Nov 2012 09:30:21 AM PST
